services:
  reverse-proxy:
    image: traefik:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=volatileasm@protonmail.com
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates

  frontend:
    build: ./
    image: drainer
    restart: always
    networks:
      - traefik-public
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-http.entrypoints=http
      - traefik.http.routers.frontend-http.rule=Host(`drainer.com`)
      - traefik.docker.network=traefik-public
      - traefik.http.routers.frontend-https.entrypoints=https
      - traefik.http.routers.frontend-https.rule=Host(`drainer.com`)
      - traefik.http.routers.frontend-https.tls=true
      - traefik.http.routers.frontend-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.frontend-http.middlewares=https-redirect

volumes:
  traefik-public-certificates:

networks:
  traefik-public:
    external: true
